# Generated by Django 5.1.5 on 2025-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritech_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vendeur_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('acheteur', 'Acheteur'), ('vendeur', 'Vendeur')], default='acheteur', max_length=10),
        ),
    ]
