# Generated by Django 5.2.1 on 2025-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritech_app', '0002_profile_is_vendeur_confirmed_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepte_contact',
            field=models.BooleanField(default=True, verbose_name="Accepte d'être contacté"),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
